[phases.setup]
nixPkgs = [
  "cairo",
  "pango",
  "gdk-pixbuf",
  "glib",
  "libffi",
  "gcc",
  "pkg-config",
  "dejavu_fonts"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
