[phases.setup]
aptPkgs = [
  "libcairo2",
  "libpango-1.0-0",
  "libpangocairo-1.0-0",
  "libgdk-pixbuf-2.0-0",
  "libffi-dev",
  "shared-mime-info",
  "fonts-dejavu-core",
  "build-essential"
]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
