[phases.setup]
aptPkgs = [
  "python3",
  "python3-pip",
  "python3-venv",
  "libcairo2",
  "libpango-1.0-0",
  "libpangocairo-1.0-0",
  "libgdk-pixbuf-2.0-0",
  "libffi-dev",
  "shared-mime-info",
  "fonts-dejavu-core",
  "build-essential"
]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv && . /opt/venv/bin/activate && python -m pip install --upgrade pip && python -m pip install -r requirements.txt"
]
[start]
cmd = "gunicorn 'app:create_app()' --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
